# This file may be used to create an environment using:
# $ conda env create -f <this file>
# platform: win-64

name: test

dependencies:
  - flask < 2.4
  - flask-bcrypt
  - pandas
  - numpy
  - mysqlclient
  - python == 3.9